### ISSUE TITLE
Very slow processing of event_posrec_many

### ISSUE THREAD

**Issue by ftoschi** [XENONnT/straxen#334] opened 2021-01-18 16:17 UTC
When changing the default configurations of a context, reprocessing the 'event_posrec_many' data type takes a very long time. In the following a minimal working example:

```
RUN_ID = '011680'
st = straxen.contexts.xenonnt_online()
st.set_config({'left_event_extension': int(3e6),
               'right_event_extension': int(3e6)})

df = st.get_df(RUN_ID, 
               ['events','event_basics', 'event_posrec_many'])
```

This happens with the following configuration:
```
	Python 3.8.5 at /dali/lgrandi/strax/miniconda3/envs/strax/bin/python
	Strax 0.13.3 at /dali/lgrandi/strax/strax/strax
	Straxen 0.14.3 at /dali/lgrandi/strax/straxen/straxen
```

Peak_positions is fast to load with the given condition (only event data kind configurations changed) and not reprocessing the event_posrec_many removes the problem.

**Comment by jorana** [comment] 2021-01-22 21:33
Hi Fanchesco, I fear there might be something going wrong even deeper, in strax. To solve this for the time beeing:

```python
st.set_config({'left_event_extension': int(3e6),
               'right_event_extension': int(3e6)})
st.make(run_id , ' event_basics' )
st.get_array(run_id, 'event_basics')
```

**Comment by jorana** [comment] 2021-04-10 15:47
With https://github.com/XENONnT/straxen/pull/420, this datatype is removed. 

The issue is the limitation of the lazy-mailbox system which is a straxen bug, partially addressed in https://github.com/AxFoundation/strax/pull/408.

Feel free to reopen if the error persists. (although strax is the better place)

**Closed by jorana** 2021-04-10 15:47 UTC
Labels: bug
