### ISSUE TITLE
Reduce file count in pulse_counts and veto_regions

### ISSUE THREAD

**Issue by JelleAalbers** [XENONnT/straxen#97] opened 2020-04-19 13:16 UTC
Currently pulse_counts and veto_regions area not rechunked on saving. That meaks we get a lot of small files, which is problematic for data storage.

If we would rechunk it, we couldn't use it for online monitoring of the pulse rate anymore (though the website doesn't support this yet) since it would only write one chunk to disk at the end of the run.

The easiest solution seems to be to have two savers: one without rechunking (for use in monitoring) and one with (for storage). The alternative would be to re-pack the data after writing it but before transferring it.

**Comment by lucrlom** [comment] 2020-05-14 17:33
The problem is that in this way the kernel of the notebook runs in timeout on dali-login1. At least in my case.

**Comment by JelleAalbers** [comment] 2020-05-15 08:20
Hi Francesco, can you be more specific? What code are you running, what error/problem do you see, how does it relate to this enhancement proposal about pulse_counts?

**Comment by lucrlom** [comment] 2020-05-17 11:07
I got the problem, is related to the amount of memory necessary to load the raw_record. We can delete this thread

**Comment by JelleAalbers** [comment] 2020-05-17 11:36
No problem, then we'll keep this issue open since it refers to something unrelated to your comment.

**Comment by jorana** [comment] 2020-06-19 13:56
This would be fixed by your #130

**Closed** 2020-07-21 08:00 UTC
Labels: enhancement
