### ISSUE TITLE
open_resource caches by filename, ignores fmt option

### ISSUE THREAD

**Issue by jmosbacher** [XENONnT/straxen#867] opened 2021-12-28 12:43 UTC
The `open_resource` method caches values by filename, leading to the fmt option being ignored when file has already been open.

**To Reproduce**
```python
import straxen
res1  = straxen.get_resource('XENONnT_numbers.json', fmt='text')
res2 = straxen.get_resource('XENONnT_numbers.json', fmt='json')
assert res1 == res2
```

**Expected behavior**
fmt option should not be ignored even when value is cached. Cache should store tuple (filename, fmt)
Any reason not to use an lru cache here?

**Versions**
straxen v1.2.1

**Comment by JoranAngevaare** [comment] 2021-12-28 12:59
This is a duplicate of #741 which is addressed in https://github.com/XENONnT/straxen/pull/856

**Closed by JoranAngevaare** 2021-12-28 12:59 UTC
Labels: bug
