### ISSUE TITLE
Rundb front-end fails when working with superruns stored in any other storage frontend. 

### ISSUE THREAD

**Issue by WenzDaniel** [XENONnT/straxen#983] opened 2022-03-21 08:14 UTC
**Describe the bug**

Rundb front-end fails when working with superruns stored in any other storage frontend.

**Comment by JoranAngevaare** [comment] 2022-03-23 08:20
Can you provide some more details?

**Comment by WenzDaniel** [comment] 2022-03-23 08:54
Sorry, I do not have the trace back at hand currently, The issue was that somewhere in the code we convert the run_id into an integer which does not work for strings. So just `raising DataNotStored` in that case would be already the solution in that case. Maybe you know already the line of code I am talking about. Otherwise let me try to find back the traceback.

**Comment by JoranAngevaare** [comment] 2022-03-30 12:18
No I actually do not since all three places where this could be is below an `if run_id.startswith('_')`: bla so I'm curious how it happened

**Comment by JoranAngevaare** [comment] 2022-04-21 13:01
Closing this issue because of reproducibility please reopen when the issue persists

**Closed by JoranAngevaare** 2022-04-21 13:01 UTC
Labels: bug
